# 场景配置文件

# 目标数量
num_targets: 100

# 目标聚集率
target_aggregation_rate: 0.6

# 目标落点中心坐标
center_drop_position: (1000, 1000, 0)

# 目标类型比例（百分比，总和应为1.0）
target_ratio:
  ballistic_missile: 0.1  # 10% 弹道导弹
  cruise_missile: 0.4     # 40% 巡航导弹
  aircraft: 0.4        # 40% 战斗机

# Target Speed (ms)
speed:
  ballistic_speed: 5500  # 弹道导弹速度
  cruise_speed: 340  # 巡航导弹速度
  aircraft_speed: 800  # 战斗机速度

# 仿真时间参数
simulation:
  total_time: 1000   # 总仿真时间（秒）
  time_step: 10    # 每个时间步长（秒）
  algorithm_step: 20.0  # 每次态势融合时间（秒）

# 输出文件夹和文件命名
output:
  base_folder: "scenario"  # 输出文件夹基础名称
  target_filename_template: "{num_targets}-targets.csv"  # 目标 CSV 文件名
